[platformio]
default_envs = cubie_c3

[env:cubie_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM4
monitor_port = COM4
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
extra_scripts = pre:scripts/fix_toolchain_path.py
build_src_filter =
    +<*>
    -<nothing_ui_test/*>
build_flags =
    -D CUBIE_SIMULATOR=0
    -D CUBIE_USE_OLED=1
    -D CUBIE_USE_GLYPH=1
lib_deps =
    file://chronos_source/src
    fbiego/ESP32Time@^2.0.6
    h2zero/NimBLE-Arduino@^2.1.0
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit SH110X@^2.1.13
    adafruit/Adafruit NeoPixel@^1.12.5

[env:nothing_ui_test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM4
monitor_port = COM4
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
build_src_filter =
    -<*>
    +<nothing_ui_test/*.cpp>
build_flags =
    -D CUBIE_USE_OLED=1
    -D CUBIE_USE_GLYPH=1
    -D CUBIE_SIMULATOR=0
    -I src/nothing_ui_test
lib_deps =
    file://chronos_source/src
    fbiego/ESP32Time@^2.0.6
    h2zero/NimBLE-Arduino@^2.1.0
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit SH110X@^2.1.13
    adafruit/Adafruit NeoPixel@^1.12.5
